// GENERATED by scripts/build-songs.mjs — do not edit by hand.
// Every youtubeId below was verified against YouTube's oEmbed endpoint.
// Verified 57/57 seeded songs.

export type RotationKey = 'udit' | 'sanu' | 'mustafa' | 'raat' | 'purane'

export type Song = {
  slug: string
  title: string
  film: string
  year: number
  rotation: RotationKey
  youtubeId: string
}

export const songs: Song[] = [
  {
    "slug": "ab-tere-bin-jee-lenge-hum-1990",
    "title": "Ab Tere Bin Jee Lenge Hum",
    "film": "Aashiqui",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "rTatsmUgmiA"
  },
  {
    "slug": "dheere-dheere-se-meri-zindagi-1990",
    "title": "Dheere Dheere Se Meri Zindagi",
    "film": "Aashiqui",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "KeyfUuXPOcY"
  },
  {
    "slug": "main-duniya-bhula-doonga-1990",
    "title": "Main Duniya Bhula Doonga",
    "film": "Aashiqui",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "otQmzlm-s7Q"
  },
  {
    "slug": "nazar-ke-saamne-1990",
    "title": "Nazar Ke Saamne",
    "film": "Aashiqui",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "uNt18l9UfjE"
  },
  {
    "slug": "ek-sanam-chahiye-1990",
    "title": "Ek Sanam Chahiye",
    "film": "Aashiqui",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "fBylcT-TWZw"
  },
  {
    "slug": "jab-koi-baat-bigad-jaye-1990",
    "title": "Jab Koi Baat Bigad Jaye",
    "film": "Jurm",
    "year": 1990,
    "rotation": "sanu",
    "youtubeId": "ln3meCI0LFM"
  },
  {
    "slug": "sochenge-tumhe-pyar-kare-na-kare-1992",
    "title": "Sochenge Tumhe Pyar Kare Na Kare",
    "film": "Deewana",
    "year": 1992,
    "rotation": "sanu",
    "youtubeId": "lFdSi01tpYM"
  },
  {
    "slug": "teri-umeed-tera-intezar-1992",
    "title": "Teri Umeed Tera Intezar",
    "film": "Deewana",
    "year": 1992,
    "rotation": "sanu",
    "youtubeId": "MnJ3kGEdfnc"
  },
  {
    "slug": "mera-dil-bhi-kitna-pagal-hai-1991",
    "title": "Mera Dil Bhi Kitna Pagal Hai",
    "film": "Saajan",
    "year": 1991,
    "rotation": "sanu",
    "youtubeId": "FsNc7I33w60"
  },
  {
    "slug": "tumse-milne-ki-tamanna-1991",
    "title": "Tumse Milne Ki Tamanna",
    "film": "Saajan",
    "year": 1991,
    "rotation": "sanu",
    "youtubeId": "thjRNwjmAdQ"
  },
  {
    "slug": "sanam-bewafa-1991",
    "title": "Sanam Bewafa",
    "film": "Sanam Bewafa",
    "year": 1991,
    "rotation": "sanu",
    "youtubeId": "2mwVKYPl4P8"
  },
  {
    "slug": "tere-dar-par-sanam-1993",
    "title": "Tere Dar Par Sanam",
    "film": "Phir Teri Kahani Yaad Aayi",
    "year": 1993,
    "rotation": "sanu",
    "youtubeId": "05o4kCUY2Ys"
  },
  {
    "slug": "is-tarah-aashiqui-ka-1994",
    "title": "Is Tarah Aashiqui Ka",
    "film": "Imtihan",
    "year": 1994,
    "rotation": "sanu",
    "youtubeId": "WufUFQurNjE"
  },
  {
    "slug": "ae-kaash-ke-hum-1994",
    "title": "Ae Kaash Ke Hum",
    "film": "Kabhi Haan Kabhi Naa",
    "year": 1994,
    "rotation": "sanu",
    "youtubeId": "Jtg2zyS_y_c"
  },
  {
    "slug": "aisa-zakhm-diya-hai-1995",
    "title": "Aisa Zakhm Diya Hai",
    "film": "Akele Hum Akele Tum",
    "year": 1995,
    "rotation": "sanu",
    "youtubeId": "3z7tf28mR90"
  },
  {
    "slug": "achha-sila-diya-1995",
    "title": "Achha Sila Diya",
    "film": "Bewafa Sanam",
    "year": 1995,
    "rotation": "sanu",
    "youtubeId": "G7AdjVDBLO8"
  },
  {
    "slug": "dil-ne-yeh-kaha-hai-dil-se-2000",
    "title": "Dil Ne Yeh Kaha Hai Dil Se",
    "film": "Dhadkan",
    "year": 2000,
    "rotation": "sanu",
    "youtubeId": "MvcNeQlqtes"
  },
  {
    "slug": "papa-kehte-hain-1988",
    "title": "Papa Kehte Hain",
    "film": "Qayamat Se Qayamat Tak",
    "year": 1988,
    "rotation": "udit",
    "youtubeId": "FEvBiayarlc"
  },
  {
    "slug": "mujhe-neend-na-aaye-1990",
    "title": "Mujhe Neend Na Aaye",
    "film": "Dil",
    "year": 1990,
    "rotation": "udit",
    "youtubeId": "LvqEcIAsh5k"
  },
  {
    "slug": "jaadu-teri-nazar-1993",
    "title": "Jaadu Teri Nazar",
    "film": "Darr",
    "year": 1993,
    "rotation": "udit",
    "youtubeId": "n_oP9Onj0r0"
  },
  {
    "slug": "tu-mere-samne-1993",
    "title": "Tu Mere Samne",
    "film": "Darr",
    "year": 1993,
    "rotation": "udit",
    "youtubeId": "Oj484P4OXD8"
  },
  {
    "slug": "tujhe-dekha-to-ye-jaana-sanam-1995",
    "title": "Tujhe Dekha To Ye Jaana Sanam",
    "film": "Dilwale Dulhania Le Jayenge",
    "year": 1995,
    "rotation": "udit",
    "youtubeId": "cNV5hLSa9H8"
  },
  {
    "slug": "pardesi-pardesi-jana-nahi-1996",
    "title": "Pardesi Pardesi Jana Nahi",
    "film": "Raja Hindustani",
    "year": 1996,
    "rotation": "udit",
    "youtubeId": "Swlik5Hfu-A"
  },
  {
    "slug": "do-dil-mil-rahe-hain-1997",
    "title": "Do Dil Mil Rahe Hain",
    "film": "Pardes",
    "year": 1997,
    "rotation": "udit",
    "youtubeId": "eKIpHujNdX0"
  },
  {
    "slug": "meri-mehbooba-1997",
    "title": "Meri Mehbooba",
    "film": "Pardes",
    "year": 1997,
    "rotation": "udit",
    "youtubeId": "k2CuG5E4OAo"
  },
  {
    "slug": "chand-chhupa-badal-mein-1999",
    "title": "Chand Chhupa Badal Mein",
    "film": "Hum Dil De Chuke Sanam",
    "year": 1999,
    "rotation": "udit",
    "youtubeId": "2knQOXevwKE"
  },
  {
    "slug": "aankhon-ki-gustakhiyan-1999",
    "title": "Aankhon Ki Gustakhiyan",
    "film": "Hum Dil De Chuke Sanam",
    "year": 1999,
    "rotation": "udit",
    "youtubeId": "7k5gM4ClRRo"
  },
  {
    "slug": "sunta-hai-mera-khuda-2000",
    "title": "Sunta Hai Mera Khuda",
    "film": "Pukar",
    "year": 2000,
    "rotation": "udit",
    "youtubeId": "cbKQHl8uMlU"
  },
  {
    "slug": "hum-tumhare-hain-sanam-2002",
    "title": "Hum Tumhare Hain Sanam",
    "film": "Hum Tumhare Hain Sanam",
    "year": 2002,
    "rotation": "udit",
    "youtubeId": "a7KBTe7lpbk"
  },
  {
    "slug": "dil-laga-liya-2002",
    "title": "Dil Laga Liya",
    "film": "Dil Hai Tumhaara",
    "year": 2002,
    "rotation": "udit",
    "youtubeId": "6qBdQzPnw4E"
  },
  {
    "slug": "main-yahaan-hoon-2004",
    "title": "Main Yahaan Hoon",
    "film": "Veer-Zaara",
    "year": 2004,
    "rotation": "udit",
    "youtubeId": "m6Y8xEfyXTs"
  },
  {
    "slug": "toh-phir-aao-2007",
    "title": "Toh Phir Aao",
    "film": "Awarapan",
    "year": 2007,
    "rotation": "mustafa",
    "youtubeId": "h5-Kq9k3zeo"
  },
  {
    "slug": "tera-mera-rishta-2007",
    "title": "Tera Mera Rishta",
    "film": "Awarapan",
    "year": 2007,
    "rotation": "mustafa",
    "youtubeId": "0J0HZrDvbjY"
  },
  {
    "slug": "mahiya-2007",
    "title": "Mahiya",
    "film": "Awarapan",
    "year": 2007,
    "rotation": "mustafa",
    "youtubeId": "vU3X1Bv18Ac"
  },
  {
    "slug": "awarapan-banjaara-2007",
    "title": "Awarapan Banjaara",
    "film": "Awarapan",
    "year": 2007,
    "rotation": "mustafa",
    "youtubeId": "zHgnRLWe_GE"
  },
  {
    "slug": "bhula-dena-2013",
    "title": "Bhula Dena",
    "film": "Aashiqui 2",
    "year": 2013,
    "rotation": "mustafa",
    "youtubeId": "II4CvWvgIsI"
  },
  {
    "slug": "zaroorat-2014",
    "title": "Zaroorat",
    "film": "Ek Villain",
    "year": 2014,
    "rotation": "mustafa",
    "youtubeId": "VMEXKJbsUmE"
  },
  {
    "slug": "tadap-tadap-ke-is-dil-se-1999",
    "title": "Tadap Tadap Ke Is Dil Se",
    "film": "Hum Dil De Chuke Sanam",
    "year": 1999,
    "rotation": "raat",
    "youtubeId": "KwiDJclWo44"
  },
  {
    "slug": "woh-lamhe-woh-baatein-2005",
    "title": "Woh Lamhe Woh Baatein",
    "film": "Zeher",
    "year": 2005,
    "rotation": "raat",
    "youtubeId": "FLKxnL7KwHw"
  },
  {
    "slug": "tujhe-bhula-diya-2010",
    "title": "Tujhe Bhula Diya",
    "film": "Anjaana Anjaani",
    "year": 2010,
    "rotation": "raat",
    "youtubeId": "-Hb2DeHvvEg"
  },
  {
    "slug": "phir-le-aya-dil-2012",
    "title": "Phir Le Aya Dil",
    "film": "Barfi",
    "year": 2012,
    "rotation": "raat",
    "youtubeId": "k6BnSIs3XUQ"
  },
  {
    "slug": "humdard-2014",
    "title": "Humdard",
    "film": "Ek Villain",
    "year": 2014,
    "rotation": "raat",
    "youtubeId": "FJ55SHCzt88"
  },
  {
    "slug": "judaai-2015",
    "title": "Judaai",
    "film": "Badlapur",
    "year": 2015,
    "rotation": "raat",
    "youtubeId": "5Keb8T1umI0"
  },
  {
    "slug": "hamari-adhuri-kahani-2015",
    "title": "Hamari Adhuri Kahani",
    "film": "Hamari Adhuri Kahani",
    "year": 2015,
    "rotation": "raat",
    "youtubeId": "f3FFOBrMmdg"
  },
  {
    "slug": "agar-tum-saath-ho-2015",
    "title": "Agar Tum Saath Ho",
    "film": "Tamasha",
    "year": 2015,
    "rotation": "raat",
    "youtubeId": "sK7riqg2mr4"
  },
  {
    "slug": "channa-mereya-2016",
    "title": "Channa Mereya",
    "film": "Ae Dil Hai Mushkil",
    "year": 2016,
    "rotation": "raat",
    "youtubeId": "284Ov7ysmfA"
  },
  {
    "slug": "bekhayali-2019",
    "title": "Bekhayali",
    "film": "Kabir Singh",
    "year": 2019,
    "rotation": "raat",
    "youtubeId": "iT25WzyC-U8"
  },
  {
    "slug": "jaane-woh-kaise-log-the-1957",
    "title": "Jaane Woh Kaise Log The",
    "film": "Pyaasa",
    "year": 1957,
    "rotation": "purane",
    "youtubeId": "xIF_XO3xCjY"
  },
  {
    "slug": "chal-ud-ja-re-panchhi-1957",
    "title": "Chal Ud Ja Re Panchhi",
    "film": "Bhabhi",
    "year": 1957,
    "rotation": "purane",
    "youtubeId": "44vSASbds9Y"
  },
  {
    "slug": "dost-dost-na-raha-1964",
    "title": "Dost Dost Na Raha",
    "film": "Sangam",
    "year": 1964,
    "rotation": "purane",
    "youtubeId": "F2TAUqfb4hY"
  },
  {
    "slug": "lag-ja-gale-1964",
    "title": "Lag Ja Gale",
    "film": "Woh Kaun Thi",
    "year": 1964,
    "rotation": "purane",
    "youtubeId": "3wAnXhoCBXQ"
  },
  {
    "slug": "zindagi-ka-safar-1970",
    "title": "Zindagi Ka Safar",
    "film": "Safar",
    "year": 1970,
    "rotation": "purane",
    "youtubeId": "vLpRfaRiDnk"
  },
  {
    "slug": "tere-bina-zindagi-se-1975",
    "title": "Tere Bina Zindagi Se",
    "film": "Aandhi",
    "year": 1975,
    "rotation": "purane",
    "youtubeId": "Zm4V6ty4K6k"
  },
  {
    "slug": "kya-hua-tera-wada-1977",
    "title": "Kya Hua Tera Wada",
    "film": "Hum Kisise Kum Naheen",
    "year": 1977,
    "rotation": "purane",
    "youtubeId": "cIVkYSm7Orw"
  },
  {
    "slug": "o-saathi-re-1978",
    "title": "O Saathi Re",
    "film": "Muqaddar Ka Sikandar",
    "year": 1978,
    "rotation": "purane",
    "youtubeId": "HBAuj9GghZ4"
  },
  {
    "slug": "chhukar-mere-man-ko-1981",
    "title": "Chhukar Mere Man Ko",
    "film": "Yaarana",
    "year": 1981,
    "rotation": "purane",
    "youtubeId": "BOLYNw3x1lE"
  },
  {
    "slug": "chitthi-aayi-hai-1986",
    "title": "Chitthi Aayi Hai",
    "film": "Naam",
    "year": 1986,
    "rotation": "purane",
    "youtubeId": "v0_IRIFYC0k"
  }
]

export const songsByRotation = (key: RotationKey): Song[] =>
  songs.filter((s) => s.rotation === key)
